# Generated by Django 5.2 on 2026-01-04 01:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Exam title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed exam description"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Time limit in minutes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional flexible data (e.g., instructions, settings)",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="When the exam opens for submissions"
                    ),
                ),
                ("end_time", models.DateTimeField(help_text="When the exam closes")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the exam is visible to students",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the exam was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the exam was last updated"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course this exam belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("true_false", "True/False"),
                        ],
                        help_text="Type of question",
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField(help_text="The question content")),
                (
                    "expected_answer",
                    models.JSONField(
                        help_text="Expected answer (format varies by question type)"
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Answer options for multiple choice questions",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        help_text="Points awarded for correct answer",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within the exam"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the question was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the question was last updated"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        help_text="The exam this question belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["exam", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["course"], name="exams_exam_course__86f0f5_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["is_published"], name="exams_exam_is_publ_c23991_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["start_time"], name="exams_exam_start_t_af0816_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["end_time"], name="exams_exam_end_tim_2da3df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["course", "is_published"], name="exams_exam_course__c14daf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["exam"], name="exams_quest_exam_id_50daa5_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["exam", "order"], name="exams_quest_exam_id_4ac027_idx"
            ),
        ),
    ]
