# Generated by Django 5.2 on 2026-01-04 01:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(blank=True, help_text="Student's text answer"),
                ),
                (
                    "answer_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured answer data (e.g., selected option, multiple values)",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        help_text="Points earned for this answer",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "max_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Maximum points available",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "grading_feedback",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed grading feedback (e.g., correctness, suggestions)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the answer was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the answer was last updated"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The question being answered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
                "ordering": ["submission", "question__order"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the submission was completed",
                        null=True,
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the submission was graded",
                        null=True,
                    ),
                ),
                (
                    "total_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Student's total score",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "max_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Maximum possible score",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                        ],
                        db_index=True,
                        default="in_progress",
                        help_text="Current submission status",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional flexible data (e.g., IP address, browser info)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the submission was started"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the submission was last updated"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        help_text="The exam being submitted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
