# Generated by Django 5.2 on 2026-01-04 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                help_text="The student who submitted",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="submission",
            field=models.ForeignKey(
                help_text="The submission this answer belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="submissions.submission",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["user"], name="submissions_user_id_ca3960_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["exam"], name="submissions_exam_id_24996e_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status"], name="submissions_status_c2b4f2_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["user", "exam"], name="submissions_user_id_fd6060_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["exam", "status"], name="submissions_exam_id_d7f546_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["submitted_at"], name="submissions_submitt_f62c88_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("user", "exam")},
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["submission"], name="submissions_submiss_da05a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["question"], name="submissions_questio_b431e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["submission", "question"], name="submissions_submiss_7df7c8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("submission", "question")},
        ),
    ]
