# Generated by Django 5.2 on 2026-01-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique course code (e.g., 'CS101')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Course title", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed course description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the course is currently active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the course was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the course was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="courses_cou_code_612388_idx"),
                    models.Index(
                        fields=["is_active"], name="courses_cou_is_acti_3c7e41_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="courses_cou_created_51cadc_idx"
                    ),
                ],
            },
        ),
    ]
